# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: Task
description: Issue to track a task
title: "Task: Your task title"
labels: ["task"]
type: 'Task'
body:
  - type: markdown
    attributes:
      value: "## <ins>Task Ticket creation</ins>"
  - type: textarea
    attributes:
      label: Description
      description: |
        Description of the Task
        What does this PR change? Why is it needed? Which task it's related to?
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Impact analysis for code changes
      options:
        - label: This change does not violate any requirements and is covered by existing requirements
        - label: This change does not violate any design decisions, architectural, detailed designs
        - label: Otherwise I have created a issue for feature/component modification
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Before requesting a review, please confirm that you have
      options:
        - label: Added/updated relevant documentation for code changes
        - label: Added/updated tests to cover the relevant code changes
        - label: Followed project coding standards and guidelines
    validations:
      required: true
