# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

# Workflow configuration for `Bazel Build & Test`
# This workflow runs Bazel build and test when triggered by specific pull request events.

name: Bazel Build & Test
on:
  pull_request:
    types: [opened, reopened, synchronize]
  merge_group:
    types: [checks_requested]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.9.1
    # TODO: Uncomment this part once the code is ready for build
    #       and define the target for it.
    # - name: Bazel build module target(s)
    #   run: |
    #     bazel build <targets>
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.9.1
    # TODO: Uncomment this part once the code is ready for test
    #       and define the targets for it.
    # - name: Bazel test module target(s)
    #   run: |
    #     bazel test <targets>
